version: "3"
services:
  db:
    image: "postgres"
    restart: "always"
    environment:
      - POSTGRES_USER=calltelemetry
      - POSTGRES_PASSWORD=changme
      - POSTGRES_DB=calltelemetry_prod
    expose: [5432]
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
  web:
    image: "calltelemetry/web:0.3.4"
    restart: "always"
    ports: ["80:4000", "22:3022"]
    environment:
      - DB_USER=calltelemetry
      - DB_PASSWORD=changeme
      - DB_HOSTNAME=db
      - DB_NAME=calltelemetry_prod
      - PORT=4000
      - SECRET_KEY_BASE=wu3JgPq0IMvIMsJJZ940biL7jVkhLvHJ9I6aqlvhgonVA2eMdOgmdEjWMFAjRKSr
