site_name: CallTelemetry
site_url: https://docs.calltelemetry.com
nav:
    - Home: index.md
    - Architecture: architecture.md
    - Licensing: licensing.md
    - Change Log: changelog.md
    - Cloud Demo: cloud.md
    - Installing:
      # - "Platform Choices": deployment/choices.md
      - "OVA Appliance": deployment/ova.md
      - "Docker": deployment/docker.md
      - "Kubernetes": deployment/k8s.md
    - User Guide:
      - "Policies": features/policy.md
      - "MCID Blocking": features/mcid.md
      - "Apps": features/apps.md
      - "App - Webhook": features/webhooks.md
      - "Organizations": features/organizations.md
    - Integration Guides:
      - "Call Control": setup/curri.md
      - "CDR": setup/cdr.md
      - "MCID Spam Tags": setup/mcid.md
    - Troubleshooting:
      - "Logs": troubleshooting/logs.md
      - "CDR": troubleshooting/cdr.md
      # - "CURRI/ECC": troubleshooting/curri.md

theme: 
  name: material
  logo: assets/logo.png
  features:
    - navigation.tabs
  font:
    text: Roboto
    code: Roboto Mono
google_analytics: ['UA-153385083-2', 'mkdocs.org']
markdown_extensions:
  - attr_list
  - admonition
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.tabbed
copyright: Copyright &copy; 2020 CallTelemetry
